#!/usr/bin/env python

import reuss
import numpy as np
import matplotlib.pyplot as plt
plt.ion()

# d = reuss.DummyDetector()
d = reuss.JungfrauDetector()

pd = reuss.take_pedestal_float(d)

fig, ax = plt.subplots()
im = ax.imshow(pd[0])


