#!/usr/bin/env python

import reuss
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
plt.ion()

from slsdet import Jungfrau, defs

path = Path('/fast_raid0_md0/May/calibration/pedestal/run_2')



d = Jungfrau()
old_period = d.period

N = 500

r = reuss.ZmqReceiver('tcp://localhost:4545')
print("gain0")
frame_numbers, data = r.receive_n(N)
np.save(path/'gain_0', data)

d.stopDetector()
d.settings = defs.FORCESWITCHG1
d.period = 0.01
d.startDetector()
print("gain1")
frame_numbers, data = r.receive_n(N)
np.save(path/'gain_1', data)


d.stopDetector()
d.settings = defs.FORCESWITCHG2
d.period = 0.01
d.startDetector()
print("gain2")
frame_numbers, data = r.receive_n(N)
np.save(path/'gain_2', data)

d.stopDetector()
d.settings = defs.DYNAMICGAIN
d.period = old_period
d.startDetector()