#!/usr/bin/env python
from reuss import ReceiverServer
from argparse import ArgumentParser


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        "-p",
        "--port",
        help="TCP control port",
        type=int,
        default=5556,
    )
    args = parser.parse_args()

    ReceiverServer(f"tcp://*:{args.port}")
