#!/usr/bin/env python

import argparse
import numpy as np


from reuss import ReceiverServer

parser = argparse.ArgumentParser()
parser.add_argument("--threads", "-t", default=8, type = int)
args = parser.parse_args()


rs = ReceiverServer(threads = args.threads)
rs.run()

