#!/usr/bin/env python

import argparse
import numpy as np
from reuss import SummingReceiver, FrameAccumulator
import reuss
import time
import os
#force interactive mode
os.environ['PYTHONINSPECT'] = 'TRUE'


# cal = reuss.load_calibration()
cal = np.ones((3, 512, 1024), dtype=np.float32)
try:
    pd = np.fromfile("/dev/shm/reuss/pedestal.bin", dtype=np.float32).reshape(3, 512, 1024)
except:
    print("No pedestal found, using zeros")
    pd = np.zeros((3, 512, 1024), dtype=np.float32)


parser = argparse.ArgumentParser()
parser.add_argument("--threads", "-t", default=8, type = int)
args = parser.parse_args()

r = SummingReceiver(args.threads)
r.set_frames_to_sum(1)
r.set_threshold(-50)

r.set_pedestal(pd)
r.set_calibration(cal)
r.start()


