#!/usr/bin/env python

import numpy as np
from reuss import SummingReceiver, FrameAccumulator
import time

pd = np.zeros((3,512,1024), dtype=np.float32)
cal = np.ones((3,512,1024), dtype=np.float32)

r = SummingReceiver()
r.set_frames_to_sum(20)
r.set_pedestal(pd)
r.set_calibration(cal)
r.start()

# time.sleep(5)

# r.stop()

# f = FrameAccumulator()
# # f.set_pedestal(pd)
# a = f.get_pedestal()