#!/usr/bin/env python
"""
Stand alone stream reader for debugging purposes.
Should not depend on anything else in reuss.


"""
import argparse
import numpy as np
import zmq


#Configuration
nrow = 514
ncol = 1030
dt = np.float32
timeout_ms = 10

parser = argparse.ArgumentParser()
parser.add_argument('-s', '--stream', type=str, default="tcp://localhost:4545", help="zmq stream")
args = parser.parse_args()

endpoint = args.stream
n_frames = 10
context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.setsockopt(zmq.RCVTIMEO, timeout_ms)
socket.setsockopt(zmq.RCVHWM, n_frames)
socket.setsockopt(zmq.RCVBUF, n_frames*1024**2*np.dtype(dt).itemsize)

socket.connect(endpoint)
socket.setsockopt(zmq.SUBSCRIBE, b"")

frames_caught = 0
frame_numbers = np.zeros(n_frames, dtype = np.int64)
data = np.zeros((n_frames, nrow, ncol), dtype = dt)
i = 0
while frames_caught < n_frames:
    #Try to read an image, if timeout then try again
    try:
        msgs = socket.recv_multipart()
        frame_numbers[i] = np.frombuffer(msgs[0], dtype = np.int64)[0]
        data[i] = np.frombuffer(msgs[1], dtype = np.float32).reshape(nrow, ncol)
        print(f'Received frame {frame_numbers[i]}')
        i+=1
    except zmq.error.Again:
        pass