#!/usr/bin/env python

import matplotlib.pyplot as plt
import reuss


endpoint = "tcp://localhost:4545"
# endpoint = "ipc://sls_raw_data"

reciver = reuss.ZmqReceiver(endpoint)

frame_numbers, data = reciver.receive_n(10)

fig, ax = plt.subplots()
im = ax.imshow(data[0])
im.set_clim(2000,8000)
plt.show()