#!/usr/bin/env python

import argparse
import matplotlib.pyplot as plt
import reuss
import os

parser = argparse.ArgumentParser()
parser.add_argument(
    "-s", "--stream", 
    help="zmq stream", 
    type=str, default="tcp://localhost:4545"
)
parser.add_argument(
    "-n", "--n_frames", 
    help="Number of frames to receive", 
    type=int, default=1
)
parser.add_argument('-i', "--interactive", help="Keep the python terminal open",
action='store_true')
args = parser.parse_args()

if args.interactive:
    #keep repl open by setting to a non empty string
    os.environ['PYTHONINSPECT'] = 'TRUE'
    plt.ion()

reciver = reuss.ZmqReceiver(args.stream, 1280*1000*2)
frame_numbers, data = reciver.receive_n(args.n_frames)

# fig, ax = plt.subplots()
# im = ax.imshow(data[0])
# im.set_clim(2000, 7000)

# if not args.interactive:
#     plt.show()

