#!/usr/bin/env python

import argparse
import matplotlib.pyplot as plt
import reuss
import os
import time

parser = argparse.ArgumentParser()
parser.add_argument(
    "-s", "--stream", 
    help="zmq stream", 
    type=str, default="tcp://localhost:4545"
)
parser.add_argument(
    "-n", "--n_frames", 
    help="Number of frames to receive", 
    type=int, default=1
)
parser.add_argument('-i', "--interactive", help="Keep the python terminal open",
action='store_true')
args = parser.parse_args()

if args.interactive:
    #keep repl open by setting to a non empty string
    os.environ['PYTHONINSPECT'] = 'TRUE'
    plt.ion()

reciver = reuss.ZmqReceiver(args.stream)
t0 = time.perf_counter()
frame_numbers, data = reciver.receive_n_float(args.n_frames)
t1 = time.perf_counter()
print(f"Time for {args.n_frames} frames: {t1-t0:.3f} Freq {args.n_frames/(t1-t0):.3f}Hz")


fig, ax = plt.subplots()
im = ax.imshow(data[0])
im.set_clim(2000, 7000)

if not args.interactive:
    plt.show()

